/* soapServer.cpp
   Generated by gSOAP 2.7.13 from emisweb.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.13 2009-06-24 12:05:50 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupDetailFullInfo"))
		return soap_serve___ns1__GroupDetailFullInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupQueInfo"))
		return soap_serve___ns1__GroupQueInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupAgentsInfo"))
		return soap_serve___ns1__GroupAgentsInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupAbndInfo"))
		return soap_serve___ns1__GroupAbndInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupIntOvfInfo"))
		return soap_serve___ns1__GroupIntOvfInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupShiftInfo"))
		return soap_serve___ns1__GroupShiftInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupGeneralInfo"))
		return soap_serve___ns1__GroupGeneralInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupPeriodInfo"))
		return soap_serve___ns1__GroupPeriodInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestIvrApplInfo"))
		return soap_serve___ns1__IvrApplInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestIvrPortInfo"))
		return soap_serve___ns1__IvrPortInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestIvrGrpInfo"))
		return soap_serve___ns1__IvrGrpInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestMailboxInfo"))
		return soap_serve___ns1__MailboxInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestUserLogin"))
		return soap_serve___ns1__UserLogin(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestUserLogout"))
		return soap_serve___ns1__UserLogout(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupList"))
		return soap_serve___ns1__GroupList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestIvrPortGroupList"))
		return soap_serve___ns1__IvrPortGroupList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestIvrAppList"))
		return soap_serve___ns1__IvrAppList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestMailAccList"))
		return soap_serve___ns1__MailAccList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestGroupAgentsMatrix"))
		return soap_serve___ns1__AgentsPerGroupInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestAgentsList"))
		return soap_serve___ns1__AgentsList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestBriefAgentsMatrix"))
		return soap_serve___ns1__BriefAgents(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestDefaultWorkspace"))
		return soap_serve___ns1__DefaultWorkspace(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestReportListData"))
		return soap_serve___ns1__ReportListData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestVoiceDNISList"))
		return soap_serve___ns1__VoiceDNISList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestEmailDNISList"))
		return soap_serve___ns1__EmailDNISList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestBriefVoiceDNISMatrix"))
		return soap_serve___ns1__BriefVoiceDNIS(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestBriefEMailDNISMatrix"))
		return soap_serve___ns1__BriefEmailDNIS(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginLogoutRequestAcdComandAgent"))
		return soap_serve___ns1__CommandAgentLoginLogout(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ReleaseResumeRequestAcd"))
		return soap_serve___ns1__CommandAgentReleaseResume(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:StartChatRequestAcd"))
		return soap_serve___ns1__CommandAgentStartChat(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:StartRecordRequestAcd"))
		return soap_serve___ns1__CommandAgentStartRecord(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestTf"))
		return soap_serve___ns1__CommandAgentTelephonyFeatures(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestSaveWorkspase"))
		return soap_serve___ns1__SaveWorkspase(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestSaveReport"))
		return soap_serve___ns1__SaveReport(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:RequestDeleteReport"))
		return soap_serve___ns1__DeleteReport(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginManagerRequestAgents"))
		return soap_serve___ns1__LoginManagerAgentsPerGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginManagerRequestGroups"))
		return soap_serve___ns1__LoginManagerGroupsPerAgent(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginLogoutRequestAcdOneAgent"))
		return soap_serve___ns1__LoginManagerOneAgentToMultiGroups(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginLogoutRequestAcdMultiAgents"))
		return soap_serve___ns1__LoginManagerMultiAgentsToOneGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginManagerRequestAvailableAgents"))
		return soap_serve___ns1__LoginManagerAvailableAgentsForGroup(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:LoginManagerRequestAvailableGroups"))
		return soap_serve___ns1__LoginManagerAvailableGroupsForAgent(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupDetailFullInfo(struct soap *soap)
{	struct __ns1__GroupDetailFullInfo soap_tmp___ns1__GroupDetailFullInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupDetailFullInfo;
	ns1__ReturnGroupDetailFullInfo.soap_default(soap);
	soap_default___ns1__GroupDetailFullInfo(soap, &soap_tmp___ns1__GroupDetailFullInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupDetailFullInfo(soap, &soap_tmp___ns1__GroupDetailFullInfo, "-ns1:GroupDetailFullInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupDetailFullInfo(soap, soap_tmp___ns1__GroupDetailFullInfo.ns1__RequestGroupDetailFullInfo, &ns1__ReturnGroupDetailFullInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupDetailFullInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupDetailFullInfo.soap_put(soap, "ns1:ReturnGroupDetailFullInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupDetailFullInfo.soap_put(soap, "ns1:ReturnGroupDetailFullInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupQueInfo(struct soap *soap)
{	struct __ns1__GroupQueInfo soap_tmp___ns1__GroupQueInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupQueInfo;
	ns1__ReturnGroupQueInfo.soap_default(soap);
	soap_default___ns1__GroupQueInfo(soap, &soap_tmp___ns1__GroupQueInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupQueInfo(soap, &soap_tmp___ns1__GroupQueInfo, "-ns1:GroupQueInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupQueInfo(soap, soap_tmp___ns1__GroupQueInfo.ns1__RequestGroupQueInfo, &ns1__ReturnGroupQueInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupQueInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupQueInfo.soap_put(soap, "ns1:ReturnGroupQueInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupQueInfo.soap_put(soap, "ns1:ReturnGroupQueInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupAgentsInfo(struct soap *soap)
{	struct __ns1__GroupAgentsInfo soap_tmp___ns1__GroupAgentsInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupAgentsInfo;
	ns1__ReturnGroupAgentsInfo.soap_default(soap);
	soap_default___ns1__GroupAgentsInfo(soap, &soap_tmp___ns1__GroupAgentsInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupAgentsInfo(soap, &soap_tmp___ns1__GroupAgentsInfo, "-ns1:GroupAgentsInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupAgentsInfo(soap, soap_tmp___ns1__GroupAgentsInfo.ns1__RequestGroupAgentsInfo, &ns1__ReturnGroupAgentsInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupAgentsInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupAgentsInfo.soap_put(soap, "ns1:ReturnGroupAgentsInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupAgentsInfo.soap_put(soap, "ns1:ReturnGroupAgentsInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupAbndInfo(struct soap *soap)
{	struct __ns1__GroupAbndInfo soap_tmp___ns1__GroupAbndInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupAbndInfo;
	ns1__ReturnGroupAbndInfo.soap_default(soap);
	soap_default___ns1__GroupAbndInfo(soap, &soap_tmp___ns1__GroupAbndInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupAbndInfo(soap, &soap_tmp___ns1__GroupAbndInfo, "-ns1:GroupAbndInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupAbndInfo(soap, soap_tmp___ns1__GroupAbndInfo.ns1__RequestGroupAbndInfo, &ns1__ReturnGroupAbndInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupAbndInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupAbndInfo.soap_put(soap, "ns1:ReturnGroupAbndInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupAbndInfo.soap_put(soap, "ns1:ReturnGroupAbndInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupIntOvfInfo(struct soap *soap)
{	struct __ns1__GroupIntOvfInfo soap_tmp___ns1__GroupIntOvfInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupIntOvfInfo;
	ns1__ReturnGroupIntOvfInfo.soap_default(soap);
	soap_default___ns1__GroupIntOvfInfo(soap, &soap_tmp___ns1__GroupIntOvfInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupIntOvfInfo(soap, &soap_tmp___ns1__GroupIntOvfInfo, "-ns1:GroupIntOvfInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupIntOvfInfo(soap, soap_tmp___ns1__GroupIntOvfInfo.ns1__RequestGroupIntOvfInfo, &ns1__ReturnGroupIntOvfInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupIntOvfInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupIntOvfInfo.soap_put(soap, "ns1:ReturnGroupIntOvfInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupIntOvfInfo.soap_put(soap, "ns1:ReturnGroupIntOvfInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupShiftInfo(struct soap *soap)
{	struct __ns1__GroupShiftInfo soap_tmp___ns1__GroupShiftInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupShiftInfo;
	ns1__ReturnGroupShiftInfo.soap_default(soap);
	soap_default___ns1__GroupShiftInfo(soap, &soap_tmp___ns1__GroupShiftInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupShiftInfo(soap, &soap_tmp___ns1__GroupShiftInfo, "-ns1:GroupShiftInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupShiftInfo(soap, soap_tmp___ns1__GroupShiftInfo.ns1__RequestGroupShiftInfo, &ns1__ReturnGroupShiftInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupShiftInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupShiftInfo.soap_put(soap, "ns1:ReturnGroupShiftInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupShiftInfo.soap_put(soap, "ns1:ReturnGroupShiftInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupGeneralInfo(struct soap *soap)
{	struct __ns1__GroupGeneralInfo soap_tmp___ns1__GroupGeneralInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupGeneralInfo;
	ns1__ReturnGroupGeneralInfo.soap_default(soap);
	soap_default___ns1__GroupGeneralInfo(soap, &soap_tmp___ns1__GroupGeneralInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupGeneralInfo(soap, &soap_tmp___ns1__GroupGeneralInfo, "-ns1:GroupGeneralInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupGeneralInfo(soap, soap_tmp___ns1__GroupGeneralInfo.ns1__RequestGroupGeneralInfo, &ns1__ReturnGroupGeneralInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupGeneralInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupGeneralInfo.soap_put(soap, "ns1:ReturnGroupGeneralInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupGeneralInfo.soap_put(soap, "ns1:ReturnGroupGeneralInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupPeriodInfo(struct soap *soap)
{	struct __ns1__GroupPeriodInfo soap_tmp___ns1__GroupPeriodInfo;
	ns1__ReturnArrayDataType ns1__ReturnGroupPeriodInfo;
	ns1__ReturnGroupPeriodInfo.soap_default(soap);
	soap_default___ns1__GroupPeriodInfo(soap, &soap_tmp___ns1__GroupPeriodInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupPeriodInfo(soap, &soap_tmp___ns1__GroupPeriodInfo, "-ns1:GroupPeriodInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupPeriodInfo(soap, soap_tmp___ns1__GroupPeriodInfo.ns1__RequestGroupPeriodInfo, &ns1__ReturnGroupPeriodInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupPeriodInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupPeriodInfo.soap_put(soap, "ns1:ReturnGroupPeriodInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupPeriodInfo.soap_put(soap, "ns1:ReturnGroupPeriodInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__IvrApplInfo(struct soap *soap)
{	struct __ns1__IvrApplInfo soap_tmp___ns1__IvrApplInfo;
	ns1__ReturnArrayDataType ns1__ReturnIvrApplInfo;
	ns1__ReturnIvrApplInfo.soap_default(soap);
	soap_default___ns1__IvrApplInfo(soap, &soap_tmp___ns1__IvrApplInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__IvrApplInfo(soap, &soap_tmp___ns1__IvrApplInfo, "-ns1:IvrApplInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__IvrApplInfo(soap, soap_tmp___ns1__IvrApplInfo.ns1__RequestIvrApplInfo, &ns1__ReturnIvrApplInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnIvrApplInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnIvrApplInfo.soap_put(soap, "ns1:ReturnIvrApplInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnIvrApplInfo.soap_put(soap, "ns1:ReturnIvrApplInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__IvrPortInfo(struct soap *soap)
{	struct __ns1__IvrPortInfo soap_tmp___ns1__IvrPortInfo;
	ns1__ReturnArrayDataType ns1__ReturnIvrPortInfo;
	ns1__ReturnIvrPortInfo.soap_default(soap);
	soap_default___ns1__IvrPortInfo(soap, &soap_tmp___ns1__IvrPortInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__IvrPortInfo(soap, &soap_tmp___ns1__IvrPortInfo, "-ns1:IvrPortInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__IvrPortInfo(soap, soap_tmp___ns1__IvrPortInfo.ns1__RequestIvrPortInfo, &ns1__ReturnIvrPortInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnIvrPortInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnIvrPortInfo.soap_put(soap, "ns1:ReturnIvrPortInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnIvrPortInfo.soap_put(soap, "ns1:ReturnIvrPortInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__IvrGrpInfo(struct soap *soap)
{	struct __ns1__IvrGrpInfo soap_tmp___ns1__IvrGrpInfo;
	ns1__ReturnArrayDataType ns1__ReturnIvrGrpInfo;
	ns1__ReturnIvrGrpInfo.soap_default(soap);
	soap_default___ns1__IvrGrpInfo(soap, &soap_tmp___ns1__IvrGrpInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__IvrGrpInfo(soap, &soap_tmp___ns1__IvrGrpInfo, "-ns1:IvrGrpInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__IvrGrpInfo(soap, soap_tmp___ns1__IvrGrpInfo.ns1__RequestIvrGrpInfo, &ns1__ReturnIvrGrpInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnIvrGrpInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnIvrGrpInfo.soap_put(soap, "ns1:ReturnIvrGrpInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnIvrGrpInfo.soap_put(soap, "ns1:ReturnIvrGrpInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__MailboxInfo(struct soap *soap)
{	struct __ns1__MailboxInfo soap_tmp___ns1__MailboxInfo;
	ns1__ReturnArrayDataType ns1__ReturnMailboxInfo;
	ns1__ReturnMailboxInfo.soap_default(soap);
	soap_default___ns1__MailboxInfo(soap, &soap_tmp___ns1__MailboxInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__MailboxInfo(soap, &soap_tmp___ns1__MailboxInfo, "-ns1:MailboxInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__MailboxInfo(soap, soap_tmp___ns1__MailboxInfo.ns1__RequestMailboxInfo, &ns1__ReturnMailboxInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnMailboxInfo.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnMailboxInfo.soap_put(soap, "ns1:ReturnMailboxInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnMailboxInfo.soap_put(soap, "ns1:ReturnMailboxInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__UserLogin(struct soap *soap)
{	struct __ns1__UserLogin soap_tmp___ns1__UserLogin;
	ns1__LoginReturnType ns1__ReturnUserLogin;
	ns1__ReturnUserLogin.soap_default(soap);
	soap_default___ns1__UserLogin(soap, &soap_tmp___ns1__UserLogin);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__UserLogin(soap, &soap_tmp___ns1__UserLogin, "-ns1:UserLogin", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__UserLogin(soap, soap_tmp___ns1__UserLogin.ns1__RequestUserLogin, &ns1__ReturnUserLogin);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnUserLogin.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnUserLogin.soap_put(soap, "ns1:ReturnUserLogin", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnUserLogin.soap_put(soap, "ns1:ReturnUserLogin", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__UserLogout(struct soap *soap)
{	struct __ns1__UserLogout soap_tmp___ns1__UserLogout;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__UserLogout(soap, &soap_tmp___ns1__UserLogout);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__UserLogout(soap, &soap_tmp___ns1__UserLogout, "-ns1:UserLogout", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__UserLogout(soap, soap_tmp___ns1__UserLogout.ns1__RequestUserLogout, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GroupList(struct soap *soap)
{	struct __ns1__GroupList soap_tmp___ns1__GroupList;
	ns1__GroupListReturnType ns1__ReturnGroupList;
	ns1__ReturnGroupList.soap_default(soap);
	soap_default___ns1__GroupList(soap, &soap_tmp___ns1__GroupList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GroupList(soap, &soap_tmp___ns1__GroupList, "-ns1:GroupList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GroupList(soap, soap_tmp___ns1__GroupList.ns1__RequestGroupList, &ns1__ReturnGroupList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupList.soap_put(soap, "ns1:ReturnGroupList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupList.soap_put(soap, "ns1:ReturnGroupList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__IvrPortGroupList(struct soap *soap)
{	struct __ns1__IvrPortGroupList soap_tmp___ns1__IvrPortGroupList;
	ns1__GenListReturnType ns1__ReturnIvrPortGroupList;
	ns1__ReturnIvrPortGroupList.soap_default(soap);
	soap_default___ns1__IvrPortGroupList(soap, &soap_tmp___ns1__IvrPortGroupList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__IvrPortGroupList(soap, &soap_tmp___ns1__IvrPortGroupList, "-ns1:IvrPortGroupList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__IvrPortGroupList(soap, soap_tmp___ns1__IvrPortGroupList.ns1__RequestIvrPortGroupList, &ns1__ReturnIvrPortGroupList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnIvrPortGroupList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnIvrPortGroupList.soap_put(soap, "ns1:ReturnIvrPortGroupList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnIvrPortGroupList.soap_put(soap, "ns1:ReturnIvrPortGroupList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__IvrAppList(struct soap *soap)
{	struct __ns1__IvrAppList soap_tmp___ns1__IvrAppList;
	ns1__GenListReturnType ns1__ReturnIvrAppList;
	ns1__ReturnIvrAppList.soap_default(soap);
	soap_default___ns1__IvrAppList(soap, &soap_tmp___ns1__IvrAppList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__IvrAppList(soap, &soap_tmp___ns1__IvrAppList, "-ns1:IvrAppList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__IvrAppList(soap, soap_tmp___ns1__IvrAppList.ns1__RequestIvrAppList, &ns1__ReturnIvrAppList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnIvrAppList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnIvrAppList.soap_put(soap, "ns1:ReturnIvrAppList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnIvrAppList.soap_put(soap, "ns1:ReturnIvrAppList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__MailAccList(struct soap *soap)
{	struct __ns1__MailAccList soap_tmp___ns1__MailAccList;
	ns1__GenListReturnType ns1__ReturnMailAccList;
	ns1__ReturnMailAccList.soap_default(soap);
	soap_default___ns1__MailAccList(soap, &soap_tmp___ns1__MailAccList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__MailAccList(soap, &soap_tmp___ns1__MailAccList, "-ns1:MailAccList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__MailAccList(soap, soap_tmp___ns1__MailAccList.ns1__RequestMailAccList, &ns1__ReturnMailAccList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnMailAccList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnMailAccList.soap_put(soap, "ns1:ReturnMailAccList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnMailAccList.soap_put(soap, "ns1:ReturnMailAccList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__AgentsPerGroupInfo(struct soap *soap)
{	struct __ns1__AgentsPerGroupInfo soap_tmp___ns1__AgentsPerGroupInfo;
	ns1__ReturnMatrixDataTypeBGperGroupArr ns1__ReturnGroupAgentsMatrix;
	ns1__ReturnGroupAgentsMatrix.soap_default(soap);
	soap_default___ns1__AgentsPerGroupInfo(soap, &soap_tmp___ns1__AgentsPerGroupInfo);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__AgentsPerGroupInfo(soap, &soap_tmp___ns1__AgentsPerGroupInfo, "-ns1:AgentsPerGroupInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__AgentsPerGroupInfo(soap, soap_tmp___ns1__AgentsPerGroupInfo.ns1__RequestGroupAgentsMatrix, &ns1__ReturnGroupAgentsMatrix);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnGroupAgentsMatrix.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnGroupAgentsMatrix.soap_put(soap, "ns1:ReturnGroupAgentsMatrix", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnGroupAgentsMatrix.soap_put(soap, "ns1:ReturnGroupAgentsMatrix", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__AgentsList(struct soap *soap)
{	struct __ns1__AgentsList soap_tmp___ns1__AgentsList;
	ns1__AgentsListReturnType ns1__ReturnAgentsList;
	ns1__ReturnAgentsList.soap_default(soap);
	soap_default___ns1__AgentsList(soap, &soap_tmp___ns1__AgentsList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__AgentsList(soap, &soap_tmp___ns1__AgentsList, "-ns1:AgentsList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__AgentsList(soap, soap_tmp___ns1__AgentsList.ns1__RequestAgentsList, &ns1__ReturnAgentsList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnAgentsList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnAgentsList.soap_put(soap, "ns1:ReturnAgentsList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnAgentsList.soap_put(soap, "ns1:ReturnAgentsList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__BriefAgents(struct soap *soap)
{	struct __ns1__BriefAgents soap_tmp___ns1__BriefAgents;
	ns1__ReturnMatrixDataTypeBG ns1__ReturnBriefAgentsMatrix;
	ns1__ReturnBriefAgentsMatrix.soap_default(soap);
	soap_default___ns1__BriefAgents(soap, &soap_tmp___ns1__BriefAgents);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__BriefAgents(soap, &soap_tmp___ns1__BriefAgents, "-ns1:BriefAgents", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__BriefAgents(soap, soap_tmp___ns1__BriefAgents.ns1__RequestBriefAgentsMatrix, &ns1__ReturnBriefAgentsMatrix);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnBriefAgentsMatrix.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnBriefAgentsMatrix.soap_put(soap, "ns1:ReturnBriefAgentsMatrix", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnBriefAgentsMatrix.soap_put(soap, "ns1:ReturnBriefAgentsMatrix", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DefaultWorkspace(struct soap *soap)
{	struct __ns1__DefaultWorkspace soap_tmp___ns1__DefaultWorkspace;
	ns1__DefaultWorkspaceReturnType ns1__ReturnDefaultWorkspace;
	ns1__ReturnDefaultWorkspace.soap_default(soap);
	soap_default___ns1__DefaultWorkspace(soap, &soap_tmp___ns1__DefaultWorkspace);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__DefaultWorkspace(soap, &soap_tmp___ns1__DefaultWorkspace, "-ns1:DefaultWorkspace", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DefaultWorkspace(soap, soap_tmp___ns1__DefaultWorkspace.ns1__RequestDefaultWorkspace, &ns1__ReturnDefaultWorkspace);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnDefaultWorkspace.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnDefaultWorkspace.soap_put(soap, "ns1:ReturnDefaultWorkspace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnDefaultWorkspace.soap_put(soap, "ns1:ReturnDefaultWorkspace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ReportListData(struct soap *soap)
{	struct __ns1__ReportListData soap_tmp___ns1__ReportListData;
	ns1__ReportListDataReturnType ns1__ReturnReportListData;
	ns1__ReturnReportListData.soap_default(soap);
	soap_default___ns1__ReportListData(soap, &soap_tmp___ns1__ReportListData);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__ReportListData(soap, &soap_tmp___ns1__ReportListData, "-ns1:ReportListData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ReportListData(soap, soap_tmp___ns1__ReportListData.ns1__RequestReportListData, &ns1__ReturnReportListData);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnReportListData.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnReportListData.soap_put(soap, "ns1:ReturnReportListData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnReportListData.soap_put(soap, "ns1:ReturnReportListData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__VoiceDNISList(struct soap *soap)
{	struct __ns1__VoiceDNISList soap_tmp___ns1__VoiceDNISList;
	ns1__DNISListReturnType ns1__ReturnVoiceDNISList;
	ns1__ReturnVoiceDNISList.soap_default(soap);
	soap_default___ns1__VoiceDNISList(soap, &soap_tmp___ns1__VoiceDNISList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__VoiceDNISList(soap, &soap_tmp___ns1__VoiceDNISList, "-ns1:VoiceDNISList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__VoiceDNISList(soap, soap_tmp___ns1__VoiceDNISList.ns1__RequestVoiceDNISList, &ns1__ReturnVoiceDNISList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnVoiceDNISList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnVoiceDNISList.soap_put(soap, "ns1:ReturnVoiceDNISList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnVoiceDNISList.soap_put(soap, "ns1:ReturnVoiceDNISList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__EmailDNISList(struct soap *soap)
{	struct __ns1__EmailDNISList soap_tmp___ns1__EmailDNISList;
	ns1__DNISListReturnType ns1__ReturnEmailDNISList;
	ns1__ReturnEmailDNISList.soap_default(soap);
	soap_default___ns1__EmailDNISList(soap, &soap_tmp___ns1__EmailDNISList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__EmailDNISList(soap, &soap_tmp___ns1__EmailDNISList, "-ns1:EmailDNISList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__EmailDNISList(soap, soap_tmp___ns1__EmailDNISList.ns1__RequestEmailDNISList, &ns1__ReturnEmailDNISList);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnEmailDNISList.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnEmailDNISList.soap_put(soap, "ns1:ReturnEmailDNISList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnEmailDNISList.soap_put(soap, "ns1:ReturnEmailDNISList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__BriefVoiceDNIS(struct soap *soap)
{	struct __ns1__BriefVoiceDNIS soap_tmp___ns1__BriefVoiceDNIS;
	ns1__ReturnMatrixDataTypeBG ns1__ReturnBriefVoiceDNISMatrix;
	ns1__ReturnBriefVoiceDNISMatrix.soap_default(soap);
	soap_default___ns1__BriefVoiceDNIS(soap, &soap_tmp___ns1__BriefVoiceDNIS);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__BriefVoiceDNIS(soap, &soap_tmp___ns1__BriefVoiceDNIS, "-ns1:BriefVoiceDNIS", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__BriefVoiceDNIS(soap, soap_tmp___ns1__BriefVoiceDNIS.ns1__RequestBriefVoiceDNISMatrix, &ns1__ReturnBriefVoiceDNISMatrix);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnBriefVoiceDNISMatrix.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnBriefVoiceDNISMatrix.soap_put(soap, "ns1:ReturnBriefVoiceDNISMatrix", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnBriefVoiceDNISMatrix.soap_put(soap, "ns1:ReturnBriefVoiceDNISMatrix", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__BriefEmailDNIS(struct soap *soap)
{	struct __ns1__BriefEmailDNIS soap_tmp___ns1__BriefEmailDNIS;
	ns1__ReturnMatrixDataTypeBG ns1__ReturnBriefEMailDNISMatrix;
	ns1__ReturnBriefEMailDNISMatrix.soap_default(soap);
	soap_default___ns1__BriefEmailDNIS(soap, &soap_tmp___ns1__BriefEmailDNIS);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__BriefEmailDNIS(soap, &soap_tmp___ns1__BriefEmailDNIS, "-ns1:BriefEmailDNIS", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__BriefEmailDNIS(soap, soap_tmp___ns1__BriefEmailDNIS.ns1__RequestBriefEMailDNISMatrix, &ns1__ReturnBriefEMailDNISMatrix);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ReturnBriefEMailDNISMatrix.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ReturnBriefEMailDNISMatrix.soap_put(soap, "ns1:ReturnBriefEMailDNISMatrix", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ReturnBriefEMailDNISMatrix.soap_put(soap, "ns1:ReturnBriefEMailDNISMatrix", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CommandAgentLoginLogout(struct soap *soap)
{	struct __ns1__CommandAgentLoginLogout soap_tmp___ns1__CommandAgentLoginLogout;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__CommandAgentLoginLogout(soap, &soap_tmp___ns1__CommandAgentLoginLogout);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CommandAgentLoginLogout(soap, &soap_tmp___ns1__CommandAgentLoginLogout, "-ns1:CommandAgentLoginLogout", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CommandAgentLoginLogout(soap, soap_tmp___ns1__CommandAgentLoginLogout.ns1__LoginLogoutRequestAcdComandAgent, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CommandAgentReleaseResume(struct soap *soap)
{	struct __ns1__CommandAgentReleaseResume soap_tmp___ns1__CommandAgentReleaseResume;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__CommandAgentReleaseResume(soap, &soap_tmp___ns1__CommandAgentReleaseResume);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CommandAgentReleaseResume(soap, &soap_tmp___ns1__CommandAgentReleaseResume, "-ns1:CommandAgentReleaseResume", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CommandAgentReleaseResume(soap, soap_tmp___ns1__CommandAgentReleaseResume.ns1__ReleaseResumeRequestAcd, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CommandAgentStartChat(struct soap *soap)
{	struct __ns1__CommandAgentStartChat soap_tmp___ns1__CommandAgentStartChat;
	ns1__ChatResponceType ns1__StartChatResponce;
	ns1__StartChatResponce.soap_default(soap);
	soap_default___ns1__CommandAgentStartChat(soap, &soap_tmp___ns1__CommandAgentStartChat);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CommandAgentStartChat(soap, &soap_tmp___ns1__CommandAgentStartChat, "-ns1:CommandAgentStartChat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CommandAgentStartChat(soap, soap_tmp___ns1__CommandAgentStartChat.ns1__StartChatRequestAcd, &ns1__StartChatResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__StartChatResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__StartChatResponce.soap_put(soap, "ns1:StartChatResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__StartChatResponce.soap_put(soap, "ns1:StartChatResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CommandAgentStartRecord(struct soap *soap)
{	struct __ns1__CommandAgentStartRecord soap_tmp___ns1__CommandAgentStartRecord;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__CommandAgentStartRecord(soap, &soap_tmp___ns1__CommandAgentStartRecord);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CommandAgentStartRecord(soap, &soap_tmp___ns1__CommandAgentStartRecord, "-ns1:CommandAgentStartRecord", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CommandAgentStartRecord(soap, soap_tmp___ns1__CommandAgentStartRecord.ns1__StartRecordRequestAcd, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CommandAgentTelephonyFeatures(struct soap *soap)
{	struct __ns1__CommandAgentTelephonyFeatures soap_tmp___ns1__CommandAgentTelephonyFeatures;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__CommandAgentTelephonyFeatures(soap, &soap_tmp___ns1__CommandAgentTelephonyFeatures);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CommandAgentTelephonyFeatures(soap, &soap_tmp___ns1__CommandAgentTelephonyFeatures, "-ns1:CommandAgentTelephonyFeatures", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CommandAgentTelephonyFeatures(soap, soap_tmp___ns1__CommandAgentTelephonyFeatures.ns1__RequestTf, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SaveWorkspase(struct soap *soap)
{	struct __ns1__SaveWorkspase soap_tmp___ns1__SaveWorkspase;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__SaveWorkspase(soap, &soap_tmp___ns1__SaveWorkspase);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SaveWorkspase(soap, &soap_tmp___ns1__SaveWorkspase, "-ns1:SaveWorkspase", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SaveWorkspase(soap, soap_tmp___ns1__SaveWorkspase.ns1__RequestSaveWorkspase, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SaveReport(struct soap *soap)
{	struct __ns1__SaveReport soap_tmp___ns1__SaveReport;
	ns1__ResponceSaveReportType ns1__ResponceSaveReport;
	ns1__ResponceSaveReport.soap_default(soap);
	soap_default___ns1__SaveReport(soap, &soap_tmp___ns1__SaveReport);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SaveReport(soap, &soap_tmp___ns1__SaveReport, "-ns1:SaveReport", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SaveReport(soap, soap_tmp___ns1__SaveReport.ns1__RequestSaveReport, &ns1__ResponceSaveReport);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ResponceSaveReport.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ResponceSaveReport.soap_put(soap, "ns1:ResponceSaveReport", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ResponceSaveReport.soap_put(soap, "ns1:ResponceSaveReport", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DeleteReport(struct soap *soap)
{	struct __ns1__DeleteReport soap_tmp___ns1__DeleteReport;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__DeleteReport(soap, &soap_tmp___ns1__DeleteReport);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__DeleteReport(soap, &soap_tmp___ns1__DeleteReport, "-ns1:DeleteReport", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DeleteReport(soap, soap_tmp___ns1__DeleteReport.ns1__RequestDeleteReport, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__LoginManagerAgentsPerGroup(struct soap *soap)
{	struct __ns1__LoginManagerAgentsPerGroup soap_tmp___ns1__LoginManagerAgentsPerGroup;
	ns1__GenListReturnType ns1__LoginManagerResponse;
	ns1__LoginManagerResponse.soap_default(soap);
	soap_default___ns1__LoginManagerAgentsPerGroup(soap, &soap_tmp___ns1__LoginManagerAgentsPerGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__LoginManagerAgentsPerGroup(soap, &soap_tmp___ns1__LoginManagerAgentsPerGroup, "-ns1:LoginManagerAgentsPerGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__LoginManagerAgentsPerGroup(soap, soap_tmp___ns1__LoginManagerAgentsPerGroup.ns1__LoginManagerRequestAgents, &ns1__LoginManagerResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__LoginManagerResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__LoginManagerGroupsPerAgent(struct soap *soap)
{	struct __ns1__LoginManagerGroupsPerAgent soap_tmp___ns1__LoginManagerGroupsPerAgent;
	ns1__GenListReturnType ns1__LoginManagerResponse;
	ns1__LoginManagerResponse.soap_default(soap);
	soap_default___ns1__LoginManagerGroupsPerAgent(soap, &soap_tmp___ns1__LoginManagerGroupsPerAgent);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__LoginManagerGroupsPerAgent(soap, &soap_tmp___ns1__LoginManagerGroupsPerAgent, "-ns1:LoginManagerGroupsPerAgent", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__LoginManagerGroupsPerAgent(soap, soap_tmp___ns1__LoginManagerGroupsPerAgent.ns1__LoginManagerRequestGroups, &ns1__LoginManagerResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__LoginManagerResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__LoginManagerOneAgentToMultiGroups(struct soap *soap)
{	struct __ns1__LoginManagerOneAgentToMultiGroups soap_tmp___ns1__LoginManagerOneAgentToMultiGroups;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__LoginManagerOneAgentToMultiGroups(soap, &soap_tmp___ns1__LoginManagerOneAgentToMultiGroups);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__LoginManagerOneAgentToMultiGroups(soap, &soap_tmp___ns1__LoginManagerOneAgentToMultiGroups, "-ns1:LoginManagerOneAgentToMultiGroups", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__LoginManagerOneAgentToMultiGroups(soap, soap_tmp___ns1__LoginManagerOneAgentToMultiGroups.ns1__LoginLogoutRequestAcdOneAgent, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__LoginManagerMultiAgentsToOneGroup(struct soap *soap)
{	struct __ns1__LoginManagerMultiAgentsToOneGroup soap_tmp___ns1__LoginManagerMultiAgentsToOneGroup;
	ns1__ResponceInfoHeaderType ns1__NoDataResponce;
	ns1__NoDataResponce.soap_default(soap);
	soap_default___ns1__LoginManagerMultiAgentsToOneGroup(soap, &soap_tmp___ns1__LoginManagerMultiAgentsToOneGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__LoginManagerMultiAgentsToOneGroup(soap, &soap_tmp___ns1__LoginManagerMultiAgentsToOneGroup, "-ns1:LoginManagerMultiAgentsToOneGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__LoginManagerMultiAgentsToOneGroup(soap, soap_tmp___ns1__LoginManagerMultiAgentsToOneGroup.ns1__LoginLogoutRequestAcdMultiAgents, &ns1__NoDataResponce);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__NoDataResponce.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__NoDataResponce.soap_put(soap, "ns1:NoDataResponce", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__LoginManagerAvailableAgentsForGroup(struct soap *soap)
{	struct __ns1__LoginManagerAvailableAgentsForGroup soap_tmp___ns1__LoginManagerAvailableAgentsForGroup;
	ns1__GenListReturnType ns1__LoginManagerResponse;
	ns1__LoginManagerResponse.soap_default(soap);
	soap_default___ns1__LoginManagerAvailableAgentsForGroup(soap, &soap_tmp___ns1__LoginManagerAvailableAgentsForGroup);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__LoginManagerAvailableAgentsForGroup(soap, &soap_tmp___ns1__LoginManagerAvailableAgentsForGroup, "-ns1:LoginManagerAvailableAgentsForGroup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__LoginManagerAvailableAgentsForGroup(soap, soap_tmp___ns1__LoginManagerAvailableAgentsForGroup.ns1__LoginManagerRequestAvailableAgents, &ns1__LoginManagerResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__LoginManagerResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__LoginManagerAvailableGroupsForAgent(struct soap *soap)
{	struct __ns1__LoginManagerAvailableGroupsForAgent soap_tmp___ns1__LoginManagerAvailableGroupsForAgent;
	ns1__GenListReturnType ns1__LoginManagerResponse;
	ns1__LoginManagerResponse.soap_default(soap);
	soap_default___ns1__LoginManagerAvailableGroupsForAgent(soap, &soap_tmp___ns1__LoginManagerAvailableGroupsForAgent);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__LoginManagerAvailableGroupsForAgent(soap, &soap_tmp___ns1__LoginManagerAvailableGroupsForAgent, "-ns1:LoginManagerAvailableGroupsForAgent", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__LoginManagerAvailableGroupsForAgent(soap, soap_tmp___ns1__LoginManagerAvailableGroupsForAgent.ns1__LoginManagerRequestAvailableGroups, &ns1__LoginManagerResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__LoginManagerResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__LoginManagerResponse.soap_put(soap, "ns1:LoginManagerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
